media: public/images
content:
  - name: settings
    label: Settings
    type: file
    path: src/content/settings.json
    fields:
      - name: siteName
        label: Site Name
        type: string
  - name: artists
    label: Artists
    type: collection
    path: src/content/artists
    fields:
      - name: name
        label: Name
        type: string
        required: true
      - name: instagram
        label: Instagram
        type: string
      - name: image
        label: Image
        type: image
      - name: body
        label: Bio
        type: rich-text
